# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: FoxDeploy.com
email: stephen@foxdeploy.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: foxdeploy
github_username:  1redone
permalink: /blog/:title.html
disqus_shortname: foxdeploy-com.disqus.com
google_analytics: UA-60348969-1
fixed_navbar: top
theme_color: '#333333'
layout: post

# Build settings
paginate: 6
markdown: kramdown
theme: bulma-clean-theme 
#remote_theme: chrisrhymes/bulma-clean-theme
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-gist    
  - jekyll-redirect-from
  - jekyll-paginate

hero_image: /assets/images/foxdeployMOUNTAINTOP_hero.webp
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Stephen Owen"
      layout: post
      hero_image: /assets/images/foxdeployMOUNTAINTOP_hero.webp
      show_sidebar: true
      hero_link: "FoxDeploy.com" 

  -
    scope:
      path: ""
      type: "pages"
    values:
      author: "Stephen Owen"
      layout: post
      hero_image: /assets/images/foxdeployMOUNTAINTOP_hero.webp
      show_sidebar: true

exclude: [node_modules]
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
