# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

excerpt_separator: <!--more-->
title: FoxDeploy.com
email: stephen@foxDeploy.com
description: >- # this means to ignore newlines until "baseurl:"
  Systems Management tails from the foxhole
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: foxdeploy
github_username:  1RedOne
permalink: /blog/:title.html
disqus_shortname: foxdeploy-com.disqus.com
google_analytics: UA-60348969-1
fixed_navbar: top
#permalink: /:year/:month:/:title.html
# Build settings
markdown: kramdown
#theme: minima
theme: bulma-clean-theme
remote_theme: chrisrhymes/bulma-clean-theme
plugins:
  - jekyll-feed
  - jekyll-gist  
  - jekyll-remote-theme
  - jekyll-redirect-from
  
hero_image: /assets/images/foxdeployMOUNTAINTOP_hero.jpg
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Stephen Owen"
      layout: post
      hero_image: /assets/images/foxdeployMOUNTAINTOP_hero.jpg
      show_sidebar: true
      hero_link: "FoxDeploy.com" 

  -
    scope:
      path: ""
      type: "pages"
    values:
      author: "Stephen Owen"
      layout: post
      hero_image: /assets/images/foxdeployMOUNTAINTOP_hero.jpg
      show_sidebar: true
      
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
